---
title: "make pretty heatmap mononucs"
author: "Uwe Schwartz"
date: "17/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
USER<-Sys.info()["user"]
work.path<- paste0("/home/",USER,"/nucMACC_Paper/data/R001_nucMacc/manuscript_figures/Fig5/ChIP_atlas/profiles/")
knitr::opts_knit$set(root.dir =work.path)
#setwd(work.path)
```

## Dependencies & Libraries

#### Load packages
```{r libraries, message=FALSE}
library(pheatmap)
library(RColorBrewer)
```

## Import data

```{r import}
peaks<-read.delim(file="../data/M1BP/GSE101554_S2_M1BP_ChIP_peaks.bed",
                  header=F)

head(peaks)
rownames(peaks)<-paste(paste(peaks$V1,peaks$V2, sep=":"),peaks$V3,sep="-")
peaks.sort<-peaks[order(peaks$V5, decreasing = T),]

### load gene sorting of heatmap
heatmap.list<-read.delim("M1BP/sortedRegions_Heatmap_nucMACCscore.txt")
head(heatmap.list)

heat.sorted.na<-heatmap.list[match(rownames(peaks.sort),
                         as.character(heatmap.list$name)),]
#remove NAs
table(is.na(match(rownames(peaks.sort),
                         as.character(heatmap.list$name))))

heat.sorted<-heat.sorted.na[!is.na(match(rownames(peaks.sort),
                         as.character(heatmap.list$name))),]

head(heat.sorted)

## load heatmap
heat.val<-read.delim("M1BP/values_Heatmap_nucMACCscores.txt", skip=2)
row.names(heat.val)<-as.character(heatmap.list$name)

heat.val.sort<-heat.val[as.character(heat.sorted$name),]
head(heat.val.sort[,1:10])
```

## Analysis

```{r Analysis}
#get samples from heatmap
#mono.nucMACC
scores.nucMACC.col<-grep("nucMACC_scores",colnames(heat.val.sort), value = T)

######################### get Profile ######################
##  nucMACC
heat.mono<-heat.val.sort[,scores.nucMACC.col[50:249]]
colnames(heat.mono)<-c("- 1 kb", rep(".",99),"center", rep(".",98),"+ 1 kb")

profile.heat<-apply(heat.mono,2,function(x) mean(x,na.rm = T))

## loess smoothing
smoothData<-function(pos=pos,profile){
    df<-data.frame(pos, profile=as.numeric(profile))

    lo.fit<-loess(profile~pos,df,span = 0.15)
    sm<-predict(lo.fit, pos)
    return(sm)
}

pdf("M1BP/profile_nucMACC_scores.pdf", width = 4, height=3)
    plot(seq(-1000,1000-10,10)+5, 
         smoothData(seq(-1000,1000-10,10)+5, profile.heat),
         type="l", 
         xlab="distance from peak center", ylab = "hyper-accessible nucleosomes",
         lwd=2, main="M1BP", col="#1B9E77")
   
dev.off()

## heatmap
colmonoMACC<-colorRampPalette(c("#984EA3","#FFFFFF","#1B9E77"))(100)

pheatmap(heat.mono[1:1000,], scale="none",
         breaks=seq(-0.3,0.3,length.out = 101),
         show_colnames = T, show_rownames = F,
         cluster_rows = F, cluster_cols = F,
          color = colmonoMACC,
         na_col = "#FFFFFF")
dev.off()

png("M1BP/nucMACCscores_heatmap_sorted.png",res = 700, width = 1000, height = 1000)
    
    pheatmap(heat.mono, scale="none",
         breaks=seq(-0.1,0.1,length.out = 101),
         show_colnames = T, show_rownames = F,
         color = colmonoMACC,
         cluster_rows = F, cluster_cols = F,
         na_col = "#FFFFFF")
    
dev.off()

heat.mono.unsorted<-heat.val[,scores.nucMACC.col[50:249]]
colnames(heat.mono.unsorted)<-c("- 1 kb", rep(".",99),"center", rep(".",98),"+ 1 kb")

png("M1BP/nucMACCscores_heatmap_unsorted.png",res = 700, width = 1000, height = 1000)
    
    pheatmap(heat.mono.unsorted, scale="none",
         breaks=seq(-0.1,0.1,length.out = 101),
         show_colnames = T, show_rownames = F,
         color = colmonoMACC,
         cluster_rows = F, cluster_cols = F,
         na_col = "#FFFFFF")
    
dev.off()
```
## Session info
```{r info}
sessionInfo()
```



