---
title: "make pretty heatmap mononucs TES"
author: "Uwe Schwartz"
date: "06/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
work.path<- "/Volumes/admin//Analysis/R001_nucMacc/manuscript_figures/Fig1/heatmaps/monoNucs_TES//"
#work.path<- "/Volumes/admin//Analysis/R001_nucMacc/manuscript_figures/Fig1/heatmaps/monoNucs//"
knitr::opts_knit$set(root.dir =work.path)
#setwd(work.path)
#out.path<-
date.x<-Sys.Date()
```

## Dependencies & Libraries

#### Load packages
```{r libraries, message=FALSE}
library(pheatmap)
library(RColorBrewer)
library(ggpubr)
```

##Import data

```{r import}
df.rpkm<-read.delim(file="../../data/expression/RPKM_protCod_genes.txt")

head(df.rpkm)

### load gene sorting of heatmap
genes.list<-read.delim("sortedRegions_Heatmap_all.txt")
head(genes.list)

genes.heat.sorted.na<-genes.list[match(as.character(df.rpkm$refSeq), 
                                       as.character(genes.list$name), nomatch = ),]
#remove NAs
table(is.na(match(as.character(df.rpkm$refSeq), as.character(genes.list$name))))

genes.heat.sorted<-genes.heat.sorted.na[!is.na(match(as.character(df.rpkm$refSeq),
                                    as.character(genes.list$name))),]

head(genes.heat.sorted)


## load heatmap
heat.val<-read.delim("values_Heatmap_all.txt", skip=2)
row.names(heat.val)<-as.character(genes.list$name)

heat.val.sort<-heat.val[as.character(genes.heat.sorted$name),]

head(heat.val.sort[,1:10])

```


## Analysis

```{r Analysis}
#get samples from heatmap
#H3 mono.nucMACC
H3.mono.nucMACC.col<-grep("H3_nucMACC_scores",colnames(heat.val.sort), value = T)

heat.mono.H3<-heat.val.sort[,H3.mono.nucMACC.col[75:250]]
colnames(heat.mono.H3)<-c("-750", rep(".",75),"TES", rep(".",98),"+ 1 kb")

#H4 mono.nucMACC
H4.mono.nucMACC.col<-grep("H4_nucMACC_scores",colnames(heat.val.sort), value = T)

heat.mono.H4<-heat.val.sort[,H4.mono.nucMACC.col[75:250]]
colnames(heat.mono.H4)<-c("-750", rep(".",75),"TES", rep(".",98),"+ 1 kb")


## heatmapcolorcode
colmonoMACC<-colorRampPalette(c("#984EA3","#FFFFFF","#1B9E77"))(100)

######################### get Profile ######################

genes.split<-split(df.rpkm$refSeq,f = df.rpkm$expr.strength)

#convert NAs to 0
woNA.H3<-heat.mono.H3
woNA.H3[is.na(woNA.H3)]<-0

##  H3.nucMACC
profile.list<-lapply(genes.split, function(x) 
    apply(woNA.H3[which(rownames(woNA.H3) %in% x),],
                                      2,function(x) mean(x,na.rm = T)))

pdf("profile_H3_monoNucs.pdf", width = 4, height=3)
    plot(seq(-750,1000,10), profile.list[["silent"]], type="l", 
         xlab="distance from TSS", ylab = "mono-nucMACC score",
         lwd=2, main="H3 mono-nucs", col="#5CB85B", ylim=c(-0.06,0.01))
    lines(seq(-750,1000,10), profile.list[["low"]], col="#FEA22B",
         lwd=2)
    lines(seq(-750,1000,10), profile.list[["mid"]], col="#357EBD",
         lwd=2)
    lines(seq(-750,1000,10), profile.list[["high"]], col="#D43F39",
         lwd=2)
dev.off()



##heatmap

pheatmap(heat.mono.H3[1:2500,], scale="none",
         breaks=seq(-0.3,0.3,length.out = 101),
         show_colnames = T, show_rownames = F,
         color = colmonoMACC,
         cluster_rows = F, cluster_cols = F,
         na_col = "#FFFFFF")
dev.off()



png("H3_mono-nucMACC_heatmap_white.png",res = 700, width = 2000, height = 2800)
    
    pheatmap(heat.mono.H3, scale="none",
         breaks=seq(-0.3,0.3,,length.out = 101),
         show_colnames = T, show_rownames = F,
         color = colmonoMACC,
         cluster_rows = F, cluster_cols = F,
         na_col = "#FFFFFF")
    
dev.off()



#### H4
#convert NAs to 0
woNA.H4<-heat.mono.H4
woNA.H4[is.na(woNA.H4)]<-0

##  H4.nucMACC
profile.list<-lapply(genes.split, function(x) 
    apply(woNA.H4[which(rownames(woNA.H4) %in% x),],
                                      2,function(x) mean(x,na.rm = T)))

pdf("profile_H4_monoNucs.pdf", width = 4, height=3)
    plot(seq(-750,1000,10), profile.list[["silent"]], type="l", 
         xlab="distance from TSS", ylab = "mono-nucMACC score",
         lwd=2, main="H4 mono-nucs", col="#5CB85B", ylim=c(-0.06,0.01))
    lines(seq(-750,1000,10), profile.list[["low"]], col="#FEA22B",
         lwd=2)
    lines(seq(-750,1000,10), profile.list[["mid"]], col="#357EBD",
         lwd=2)
    lines(seq(-750,1000,10), profile.list[["high"]], col="#D43F39",
         lwd=2)
dev.off()


pheatmap(heat.mono.H4[1:2500,], scale="none",
         breaks=seq(-0.5,0.5,length.out = 101),
         show_colnames = T, show_rownames = F,
         color = colmonoMACC,
         cluster_rows = F, cluster_cols = F,
         na_col = "#FFFFFF")
dev.off()


png("H4_mono-nucMACC_heatmap_white.png",res = 700, width = 2000, height = 2800)
    
    pheatmap(heat.mono.H4, scale="none",
         breaks=seq(-0.3,0.3,length.out = 101),
         show_colnames = T, show_rownames = F,
         color = colmonoMACC,
         cluster_rows = F, cluster_cols = F,
         na_col = "#FFFFFF")
    
dev.off()



```


##Session info
```{r info}
sessionInfo()
```



