---
title: "Plot Motifs"
author: "Uwe Schwartz"
date: "27/01/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
USER<-Sys.info()["user"]
work.path<- paste0("/home/",USER,"/nucMACC_Paper/data/R001_nucMacc/manuscript_figures/Fig4/motifs/")
knitr::opts_knit$set(root.dir =work.path)
```

## Dependencies & Libraries

#### Load packages
```{r libraries, message=FALSE}
library(ggplot2)
library(stringr)
```

```{r code}
ndr.txt<-read.delim("NDR/knownResults.txt")
unstabl.txt<-read.delim("unstableNuc//knownResults.txt")

head(unstabl.txt)
head(ndr.txt)
#select significant
ndr<-ndr.txt[exp(ndr.txt$Log.P.value)< 0.05,"Motif.Name"]
unstbl<-unstabl.txt[exp(unstabl.txt$Log.P.value)< 0.05,"Motif.Name"]

df.unstabl<-unstabl.txt[match(c(unstbl,ndr),unstabl.txt$Motif.Name),
            c("Motif.Name","Log.P.value", "X..of.Target.Sequences.with.Motif")]
df.unstabl$class<-"unstable"

df.ndr<-ndr.txt[match(c(unstbl,ndr),ndr.txt$Motif.Name),
            c("Motif.Name","Log.P.value", "X..of.Target.Sequences.with.Motif")]
df.ndr$class<-"NDR"

df<-rbind(df.ndr,df.unstabl)
df$Motif.Name<-factor(df$Motif.Name, levels=df.unstabl$Motif.Name[
    order(df.unstabl$Log.P.value, decreasing = T)])

df$class<-relevel(as.factor(df$class),"unstable")

df$percent.with.Motif<-as.numeric(str_sub(df$X..of.Target.Sequences.with.Motif,1 ,-2))

g<-ggplot(df, aes(class,Motif.Name, color=(-log10(exp(Log.P.value))),
               size=(-log10(exp(Log.P.value)))))+
    geom_point()+theme_bw()+
    scale_color_gradient(low="blue", high="red", limits=c(1.3,10),
                         name = "-log(p-value)")

print(g)

# Save bubble plot for the motifs
pdf("bubblePlot_Motifs.pdf", width=6.5, height=3)
    print(g)
dev.off()
```

##Session info
```{r info}
sessionInfo()
```